### ISSUE TITLE
Subdecks from Anki SRS

### ISSUE THREAD

**Issue by MarcoSchicke** [AnkiUniversal/Anki-Universal#1]
First: Its a very nice APP!
I like the design with the tiles, and the font changes for editingand Night mode.

I only miss the Sync with Ankiweb to use it with Ankidroid.
And Subdecks from ankidroid are not showed as sub decks.

But for the first release, nice!

**Comment by AnkiUniversal** [comment]
Thank you for your feedback,

Sub-decks are not officially supported yet because the designer still has no idea how to show parent-child relationships in tiles :). Thought they should still work as expected as in other versions.

The code for syncing with Ankiweb has actually been translated and done some basic local tests in pre-realease. However, we haven't tested with the real Ankiweb yet because we would need Daniel's permission to do that. 

Another reason is that the way we implement media folder is different with other versions. Thus, I'm affraid we can't sync media files directly through Ankiweb. So we have to find a solution for this before implementing syncing with Ankiweb.

**Comment by MarcoSchicke** [comment]
Maybe I should have made 2 issues with that.
I thought about how to Visualize Parent and Child decks. I dont know if this is an option and if the API supports it. Hope its understanable.
![visualisation child decks](https://cloud.githubusercontent.com/assets/7468668/17306209/199d3144-582f-11e6-9300-ff10b4e0c8f8.png)

For the Syncing "Issue":
If Damien would sadly deny access to his Ankiweb server maybe someone can write Addons for the other versions of Anki to sync with Onedrive. So no access to his server needed and also the problem with the media could get solved this way. But also I've no Idea if Microsoft supports such accesses to Onedrive and if its not to troublesome because of different programing languages and operating systems.

You've done excellent work till now 👍

**Comment by AnkiUniversal** [comment]
I think it's doable. But one of the problems is how do let users know which deck has sub-decks and how to navigate between them. This will be our next priority after adding new UI features in search page and note editor.

Syncing with OneDrive on other OS is possible because Microsoft provide API for them. We may go with this direction if there are no other ways.
