### ISSUE TITLE
Settings help

### ISSUE THREAD

**Issue by siltsunrise** [AnkiUniversal/Anki-Universal#10]
Hi, I love your app, thanks for letting me grab my anki deck on my new phone! A real boon for travel.
I have a couple questions. 

1 - I changed my daily card limits in anki (ankiweb) but when I import the deck to anki universal, it reverts to the anki (ankiweb) default of 20/100 new/review cards. I see no way to tweak that in anki universal. Is it possible? Is that something you aim to implement in the future?

2 - I tried to create a cram/custom deck with my whole deck of 2309 cards in anki universal (to skip the timed repeat function; I prefer a straight run-through of my entire deck) but it ends up limited to 1000 cards,  once I'm back in the main deck screen, defeating my aim.
Is there any way to increase this? Could you not code 9999 in instead of 1000? Sounds easy from a non-programmer's perspective. ;)
- And even then, I noticed that it is doing the old anki algorithm thing, and when I stop studying, there are even more cards waiting for me next time. 
Can I not create a simple, straight, one at a time, run-through of my deck somehow?
Thanks for any help!

PS You guys still need to add an option to the mobile version menu to allow syncing with ankiweb! I worked around it, but twould be handy. :) It's on the PC version, but not the mobile.
And I'm curious, how you make any money off this? It's free! ??

**Comment by AnkiUniversal** [comment]
Hi,

Starting from July 2017, you can sync with AnkiWeb by changing your sync service in Menu/Settings/Sync. However, your phone or PC Windows will need to update to Anniversary Update (release in 2016) or higher.  Older Windows 10 version has some problems with API used for syncing.

1. 
- In all Anki versions, Default option is not imported together with your decks. Thus, in Anki Universal we do not let users change it. However, you can create a new option group by right click (or press and hold) on your deck and choose **Options** then press on the plus button on the right. 
- Otherwise, you can sync with AnkiWeb instead of importing. 

2.
- If you choose 2309 cards, you custom deck actually has 2309 cards. It just shows 1000 because of a hard limit. If you review them, you'll see that your new cards are automatically increased when you go back to the deck select page. For example, if you review 3 cards, it'll go from 1000 to 997 (new) + 3 (due) in the review page. Go back to the deck select page, it will show 1000 (new) + 3 (due). This is the default behavior of all Anki versions on all decks because of performance reason. 
- Cram mode allows you to run through all cards of your deck, though you still need to view a card 2 times if it's a new card. 

We do not make any money off this :)

**Comment by siltsunrise** [comment]
Thanks for the quick and detailed reply! So that's where the options are hiding!
- I still see only two options under the settings/sync in the mobile version: automatically sync on startup, and also sync media files. I guess the default is to sync with ankiweb?
- I did a sync but it left me with nothing, though my ankiweb has a deck waiting. Had to import the deck again to use it.
- What is sync syncing with, exactly, if not ankiweb? Did I just hit a glitch?

**Comment by AnkiUniversal** [comment]
Hi,

It seems like your phone might not be updated to Anniversary Update, which is required to get the latest version of the app. In old versions, it can only sync to OneDrive. In other words, your phone Windows build number must be larger or equal to **10.0.14393**

Could you tell us your phone model? If I remember correctly, Microsoft does not allow all models to update to Anniversary Update.

**Comment by siltsunrise** [comment]
Hi, I just updated it, so it should be the latest. Model is lumia 640.
I'll go see if I can find the windows version. Thanks!

**Comment by AnkiUniversal** [comment]
Hi,

- To see the OS build, please go to **All Settings**. Enter **About** into the search bar then press on the searched result. Under **Device information** press on **More infor**, you'll see your phone OS build.
- If the build is correct but you still can't get the latest app package, you can uninstall the app and then re-install it again.

- If re-installing also does not work, you can download the package directly on our [release page](https://github.com/AnkiUniversal/Anki-Universal/releases/download/1.3.1/AnkiU_1.3.1.0_x86_x64_arm.appxbundle)
- To install an app from a package you need to enable **Sideload apps** in **All Settings/For developers**. Please also uninstall the app first. Then, put the package into your phone (Document or Download folder). Use the default **File Explorer** app of your Phone to navigate to the package, press on it to open, and choose **Install**. Do not close **File Explorer** app. After a while, your phone will finish installing the package (no message is shown after installing so you have to check it in start screen>**swipe right**.)

**Comment by siltsunrise** [comment]
That release is for PC, not mobile, as far as I can tell.
I see no link for a mobile version on there. Is there one?
My mobile win10 version is indeed, not the anniversary, and my phone says
I'm all updated.

**Comment by siltsunrise** [comment]
I try installing that bundle, and nothing happens, thus (because is says
86/64 in the title) I'm guessing that's for pc...

**Comment by siltsunrise** [comment]
And my phone is on the list which is eligible for the anniversary. Still
won't grab it, for some reason. I wonder if one can sideload it..no luck
finding anything online for that.

**Comment by AnkiUniversal** [comment]
Hi,

The release package is for both PC and mobile (x86, x64, and arm.) 
Since your phone is not updated to Anniversary build, you can't install the package.
Depending on your region, it might take a while to get the latest OS update. Though I suggests you get support directly from Microsoft.

If all else fails, you can use OneDrive sync service instead of AnkiWeb to sync between your Phone and your PC.

**Comment by siltsunrise** [comment]
Ah, I misunderstood. One drive shut me out, but I"ll play with it and
see if I can manage. Not a biggie to just update my deck manually in
any case. Thanks for the help!

**Comment by siltsunrise** [comment]
So I got the anniversary build installed. Some bug wouldn't do it, but I tried again, and it worked. Downloaded the latest anki u. and set it to sync with ankiweb, and it worked like a charm. Thanks for the help and super app!

**Comment by AnkiUniversal** [comment]
Hi, I'm glad that you solved the problem. Feel free to contact us again if you encounter other problems.
