### ISSUE TITLE
Choosing to mark cards as leeches corrupts database/crashes the app

### ISSUE THREAD

**Issue by Fredddi43** [AnkiUniversal/Anki-Universal#11]
I have a deck in which I apparently hit leech status on a card today, upon which the popup asked me if I wanted to mark cards or remove them. Selecting 'No' in this dialogue, therefore choosing to only mark cards as leeches, seems to either corrupt the database or cause the app to crash forever. A reinstall of the app and starting from an earlier Ankiweb backup fixed the issue, but upon hitting the same popup choosing 'No' yields the same bug. I have made a copy of my Anki-Universal data folder that, whenever copied into the app, reproduces this behavior. I can upload it if needed.

Love the app otherwise, except for this and a sync bug I hit upon earlier, but I'm sure you guys are gonna squash 'em.

**Comment by AnkiUniversal** [comment]
Hi, 

  Thanks for notifying us about this bug. This is due to some incompatibilities between older versions and the newest version. We'll push a new update to the store soon since this is a critical bug.

   You also mentioned that you hit a sync bug. Could to tell us how to reproduce it?

Best regards,
Anki Universal Team

**Comment by Fredddi43** [comment]
I have since reinstalled my system, and it has not occurred again, therefore I've been unable to reproduce it myself. But while it was happening, it would show the sync window, stating a download rate of 3 kb/s and then just sit there for hours. A network monitor actually showed several hundreds of kb/s of activity, but it never actually finished. Sorry I don't have more information for you.

**Comment by AnkiUniversal** [comment]
Hi, no problems. Thank you again for contacting us.

**Comment by Fredddi43** [comment]
As the sync bug has once again made an appearance, I have attached my AnkiUniversal folder from Appdata, which will sync over Onedrive, but not using Anki Web. Verified it fails on both my laptop and my Desktop, so I hope this will help you reproduce the issue. There was also an error message which I unfortunately did not get a screenshot of, if you have a log file somewhere I'd be happy to upload it for you.

[36558AnkiUniversal.AnkiUniversal_qh2hfqm01f5q4.zip](https://github.com/AnkiUniversal/Anki-Universal/files/1190525/36558AnkiUniversal.AnkiUniversal_qh2hfqm01f5q4.zip)

**Comment by Fredddi43** [comment]
As the sync bug has once again made an appearance, I would like to attach a copy of my library,, which will sync over Onedrive, but not using Anki Web. Verified it fails on both my laptop and my Desktop, so I hope this will help you reproduce the issue. There was also an error message which I unfortunately did not get a screenshot of, if you have a log file somewhere I'd be happy to upload it for you. However, I am unsure how much of my Appdata AnkiUniversal folder I can upload without giving away my personal Ankiweb settings. Would the LocalState folder suffice?

**Comment by AnkiUniversal** [comment]
Hi, the LocalState folder should be good enough, though I have received your file from the previous post through email. We do not store AnkiWeb user name and password. Only the key needed to access AnkiWeb is stored by using the password vault of Windows 10, which is encrypted. You can change to a new key anytime by re-logging into AnkiWeb.

As for the sync bug, unfortunately I couldn't reproduce it by using your collection data. This is probably because I have to do a full upload to AnkiWeb.
To temporarily by bass this bug you can try forcing a full upload by going to **Settings/Sync/Force Full Sync**, then choose **UPLOAD** when you try to sync again.

**Comment by Fredddi43** [comment]
I have tried forcing a full upload, unfortunately it makes no difference, the sync process does not get far enough to ask me if I would like to up- or download, it just stalls immediately. I have however bypassed this bug in the past by uninstalling Anki Universal and restoring from AnkiWeb, which sadly loses my study progress. I will try creating a seperate AnkiWeb account and forcing a full sync to that and see if it makes a difference.

**Comment by Fredddi43** [comment]
I was able to resolve the sync issue by creating a seperate account, uploading the collection to that account, and then switching back to my normal account which allowed me to perform a full sync without the process getting stuck. Should the issue arise I again i will make sure to capture a screenshot of the error message for you. Thanks for your help.

**Comment by AnkiUniversal** [comment]
Hi, thanks for informing us. Since the sync process didn't start, I think this bug might relate to the key needed to access to AnkiWeb. Thus, re-logging fixed the issue. 

Please let us know if you meet this bug again. I'll also try to re-create it on my end.
