### ISSUE TITLE
Import transcription, definition and pronunciation from offline dictionary format

### ISSUE THREAD

**Issue by i1459193** [AnkiUniversal/Anki-Universal#19]

**Comment by AnkiUniversal** [comment]
Hi, we won't support this because it can be more harmful than good. Even with the help of flash cards, learning words directly from dictionary won't help you to memorize them for long. 
For more details: https://apps.ankiweb.net/docs/manual.html#downloading-shared-decks.

Best regards,
Anki Universal Team
