### ISSUE TITLE
New feature request:  TTS support

### ISSUE THREAD

**Issue by theFool32** [AnkiUniversal/Anki-Universal#3]
I used anki universal for days and find it wonderful.
I open this to ask if there is a plan to support text-to-speech. It's useful when remembering words without media file.And it seems that windows phone provides related api.

Thanks for your great work. 👍

**Comment by AnkiUniversal** [comment]
Hi,

 It's true that the api of Microsoft supports TTS on both mobile and PC. 
 We're also considering adding TTS support and maybe some voice commands when reviewing cards (like answering Good or Hard by using voice, so it's easier to use the app with one hand on mobile.)
 
 However, right now we're working on adding sub-deck support first, then, enabling font color selection on mobile. That's why it's might take a while (months) until we can work on TTS.
