### ISSUE TITLE
App is pending

### ISSUE THREAD

**Issue by Atrebas** [AnkiUniversal/Anki-Universal#6]
Hi,
This is a great app, one of my favorite. But unfortunately, since yesterday, the app is 'pending' and the icon is greyed out (windows phone). Rebooting the phone has no effect.
Any suggestion?
Thanks.

**Comment by AnkiUniversal** [comment]
Dear Atrebas,

 Sorry for the late reply as we do not monitor this page regularly.
 Yesterday we put a new update to the store so you will need to update the app first. Normally this is done automatically. However, there might be some problems happening during the downloading process.

 Please try opening the store app of Windows Phone, then press on the menu button on the top left, and go to "Downloads and updates". If you can see the app please retry the update.

Best Regards,
Anki Universal Team.

**Comment by Atrebas** [comment]
Thanks for answer.
The update (to 1.2.2.0 I think) worked but it didn't fix the issue...

**Comment by AnkiUniversal** [comment]
Hi,

Sometime WP backup can prevent apps to launch. If the backup happens when the app is updated, then it might get stuck in this state ([same on WP 8.1](http://www.kapilarya.com/fix-whatsapp-tile-greyed-windows-phone-8-1)). Please try to back up your phone to see if the problem still persists.

If this still won't fix the issue and you have synced your collection to OneDrive, then you can re-install the app and re-sync it. Please note that this will delete all your unsynced data, so do not try this option if you are not certain. 

Best Regards,
Anki Universal Team.

**Comment by Atrebas** [comment]
Thanks for the support.
I finally reinstalled (and lost my unsynced data...).
Great app anyway.
