### ISSUE TITLE
Can't sync with Onedrive account on PC and mobile.

### ISSUE THREAD

**Issue by anthuansales** [AnkiUniversal/Anki-Universal#9]
After give permission on app the issue still the same.
![printe](https://user-images.githubusercontent.com/29899920/27841308-894a46a2-60d6-11e7-98ec-fc58b41a97f4.png)

![print](https://user-images.githubusercontent.com/29899920/27840381-c84cce7c-60ce-11e7-8a2a-efd0469434b0.png)

**Comment by AnkiUniversal** [comment]
Hi,

This error might happen due to some global settings in your Microsoft or OneDrive account. It could also happen because the permission was still putting on hold and not reflected to the app yet. Unfortunately, there is little we can do about this as it's more about Microsoft side.

Starting from 04/07/2017, the app now supports syncing with AnkiWeb which supports multi-platforms (iOS, Android, Linux) and delta-sync. You can change your sync service to AnkiWeb in Settings/Sync. If you do not have an account, you can register one for free on AnkiWeb.

Best regards,
Anki Universal Team.
